version: '3.8'

services:

  # For now, we'll be using itzg's preconfigured bungeecord and minecraft server containers just to get everything running
  # https://github.com/itzg/docker-minecraft-server/ 
  # https://github.com/itzg/docker-bungeecord
  # This SHOULD change in the future when someone has enough time to swap this out with something assembled from scratch with the orignal Paper and Velocity jars.
  #
  # ...actually, nah. This works great. :)

  #######################################################
  # hub Profile - The main Minecraft hub world. Includes a Velocity proxy configured for modern forwarding, and a void world running on Paper.
  main-proxy:
    hostname: main-proxy
    container_name: main-proxy
    profiles: ["hub"]
    image: itzg/bungeecord:java17
    ports:
      - "25565:25565"
    environment:
      UID: 1002 #Minecraft user
      GID: 1003 #Minecraft group
      TYPE: VELOCITY
      VELOCITY_VERSION: latest
      MEMORY: 512m
      JVM_XX_OPTS: "-XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15"
      PLUGINS: https://github.com/ViaVersion/ViaVersion/releases/download/4.4.2/ViaVersion-4.4.2.jar,https://github.com/ViaVersion/ViaBackwards/releases/download/4.4.2/ViaBackwards-4.4.2.jar
    restart: always
    volumes:
      - ./servers/main-proxy:/server
    links:
      - main-hub

  main-hub:
    hostname: main-hub
    container_name: main-hub
    profiles: ["hub"]
    image: itzg/minecraft-server:java17
    ports:
      - "30065:25565"
    environment:
      UID: 1002 #Minecraft user
      GID: 1003 #Minecraft group
      TYPE: PAPER
      VERSION: latest
      MEMORY: 1024m
      USE_AIKAR_FLAGS: "TRUE"
      EULA: "TRUE"
      SPIGET_RESOURCES: 19254,27448,25391,102902 #ViaVersion, ViaBackwards, VoidGen, NoEncryption
      #EXEC_DIRECTLY: true
      # enable env variable replacement
      REPLACE_ENV_VARIABLES: "true"
      # define an optional prefix for env variables we want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
      # actual variables
      CFG_FORWARDING_SECRET_FILE: "/forwarding.secret"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./servers/main-hub:/data

  #######################################################
  # yoahtl-creative Profile
  yoahtl-creative:
    hostname: yoahtl-creative
    container_name: yoahtl-creative
    profiles: ["yoahtl-creative"]
    image: itzg/minecraft-server:java17
    ports:
      - "30066:25565"
    environment:
      UID: 1002 #Minecraft user
      GID: 1003 #Minecraft group
      TYPE: PAPER
      VERSION: 1.18.2
      MEMORY: 7168m
      USE_AIKAR_FLAGS: true
      EULA: "TRUE"
      EXTRA_ARGS: '--universe ./worlds/'
      #EXEC_DIRECTLY: true
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./servers/yoahtl-creative:/data
    depends_on:
      - yoahtl-civdb
  yoahtl-civdb:
    hostname: yoahtl-civdb
    container_name: yoahtl-civdb
    user: minecraft
    profiles: ["yoahtl-creative"]
    image: mariadb:10.7.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
    command: --max-connections 500
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 30s
      retries: 10
    restart: unless-stopped
    volumes:
      - ./servers/yoahtl-creative/mariadb:/var/lib/mysql
      - ./servers/yoahtl-creative/mariadb-provision:/docker-entrypoint-initdb.d

secrets:
  forwarding_secret:
    file: /forwarding.secret