version: '3.8'

services:
  yoahtl-creative:
    hostname: yoahtl-creative
    image: itzg/minecraft-server:java17
    ports:
      - "30067:25565"
    environment:
      TYPE: PAPER
      VERSION: 1.18.2
      MEMORY: 7168m
      USE_AIKAR_FLAGS: true
      EULA: "TRUE"
      EXTRA_ARGS: '--universe ./worlds/'
      EXEC_DIRECTLY: true
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./yoahtl-creative:/data