version: '3.8'

services:

  # For now, we'll be using itzg's preconfigured bungeecord and minecraft server containers just to get everything running
  # https://github.com/itzg/docker-minecraft-server/ 
  # https://github.com/itzg/docker-bungeecord
  # This SHOULD change in the future when someone has enough time to swap this out with something assembled from scratch with the orignal Paper and Velocity jars.

  yoahtl-creative:
    hostname: yoahtl-creative
    container_name: yoahtl-creative
    image: itzg/minecraft-server:java17
    ports:
      - "25565:25565"
    environment:
      TYPE: PAPER
      VERSION: 1.18.2
      MEMORY: 7168m
      USE_AIKAR_FLAGS: true
      EULA: "TRUE"
      EXTRA_ARGS: '--universe ./worlds/'
      #EXEC_DIRECTLY: true
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./servers/yoahtl-creative:/data
    depends_on:
      - mariadb
  mariadb:
    hostname: yoahtl-civdb
    container_name: yoahtl-civdb
    image: mariadb:10.7.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
    command: --max-connections 500
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    volumes:
      - ./servers/yoahtl-creative/mariadb:/var/lib/mysql
      - ./servers/yoahtl-creative/mariadb-provision:/docker-entrypoint-initdb.d
