version: '3.8'

services:

  # For now, we'll be using itzg's preconfigured bungeecord and minecraft server containers just to get everything running
  # https://github.com/itzg/docker-minecraft-server/ 
  # https://github.com/itzg/docker-bungeecord
  # This SHOULD change in the future when someone has enough time to swap this out with something assembled from scratch with the orignal Paper and Velocity jars.
  proxy:
    hostname: proxy
    image: itzg/bungeecord:java17
    ports:
      - "25565:25565"
    volumes:
      - ./servers/proxy:/server
    environment:
      TYPE: VELOCITY
      VELOCITY_VERSION: latest
      MEMORY: 512m
      JVM_XX_OPTS: "-XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15"
      #BUNGEE_JAR_REVISION: "1"
      #REPLACE_ENV_VARIABLES: "true"
    restart: unless-stopped
    links:
      - "hub"
  hub:
    hostname: hub
    image: itzg/minecraft-server:java17
    ports:
      - "30066:25565"
    environment:
      TYPE: PAPER
      VERSION: latest
      MEMORY: 1024m
      USE_AIKAR_FLAGS: true
      EULA: "TRUE"
      #EXEC_DIRECTLY: true
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./servers/hub:/data

  